"""
generate_comparison_grid.py
----------------------------
Generate a publication-quality comparison grid figure like Figure 8:

    "HASTE improves visual scaling. We compare images generated by
     SiT-XL/2+REPA and SiT-XL/2+HASTE at different training iterations."

Layout:
  - Rows  : methods (e.g. REPA, HASTE) × labels/seeds selected by you
  - Cols  : checkpoint iterations (e.g. 100K, 200K, 400K)
  - Groups: one "column group" per (label, seed) combination you choose to keep

Usage example (edit CKPT_CONFIGS and SAMPLES below to your needs):

    CUDA_VISIBLE_DEVICES=4 python generate_comparison_grid.py \
        --method-a-label "SiT-XL/2+iREPA" \
        --method-b-label "SiT-XL/2+Attn.Scaf." \
        --method-a-ckpts /workspace/iREPA/ldm/exps/irepa_conv_1.0/checkpoints/0100000.pt /workspace/iREPA/ldm/exps/irepa_conv_1.0/checkpoints/0200000.pt /workspace/SIT/iREPA-collections/0400000.pt \
        --method-b-ckpts /workspace/SIT/exps/conv_3_kv_2.0/checkpoints/0100000.pt /workspace/SIT/exps/conv_3_kv_2.0/checkpoints/0200000.pt /workspace/SIT/exps/conv_3_kv_2.0/checkpoints/0400000.pt \
        --ckpt-labels 100K 200K 400K \
        --class-labels 207 208 235 250 267 245 246 234 231 263 385 386 101 344 346 347 15 80 81 85 86 127 849 505 968 \
        --seeds 0 1 2 42 72 142 162 \
        --cfg-scale 1.0 \
        --num-steps 250 \
        --mode ode \
        --out output/2
CUDA_VISIBLE_DEVICES=0 python generate_comparison_grid_v2.py \
    --method-a-label "SiT-XL/2 + iREPA" \
    --method-b-label "SiT-XL/2 + AttnScaf" \
    --method-a-ckpts /workspace/iREPA/ldm/exps/irepa_conv_1.0/checkpoints/0100000.pt /workspace/iREPA/ldm/exps/irepa_conv_1.0/checkpoints/0200000.pt /workspace/SIT/iREPA-collections/0400000.pt \
        --method-b-ckpts /workspace/SIT/exps/conv_3_kv_2.0/checkpoints/0100000.pt /workspace/SIT/exps/conv_3_kv_2.0/checkpoints/0200000.pt /workspace/SIT/exps/conv_3_kv_2.0/checkpoints/0400000.pt \
    --ckpt-labels 100K 200K 400K \
    --class-labels 207 88 2 400 849 325 \
    --seeds 0 1 2 42 72 142 \
    --cfg-scale 1.0 --num-steps 250 --mode ode \
    --out comparison_grid.png

Arguments
---------
--method-a-ckpts   : 3 checkpoint paths for method A (in iteration order)
--method-b-ckpts   : 3 checkpoint paths for method B (in iteration order)
--method-a-label   : row label for method A
--method-b-label   : row label for method B
--ckpt-labels      : display labels for columns, e.g. "100K 200K 400K"
--class-labels     : ImageNet class IDs for each column group
--seeds            : random seeds (one per column group)
--cfg-scale        : classifier-free guidance scale (paper uses 4.0)
--num-steps        : ODE/SDE steps
--mode             : 'ode' or 'sde'
--resolution       : 256 or 512
--out              : output PNG (or PDF) path

The script generates MORE images than shown (all combinations of the provided
seeds × labels) so you can pick your favourites.  Set --batch-all to True
to dump every combination as a separate PNG for easy selection.
"""

import argparse
import math
import os
import sys

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from PIL import Image

# ──────────────────────────────────────────────────────────────
# SIT codebase imports
# ──────────────────────────────────────────────────────────────
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from models.sit import SiT_models
from models.autoencoder import VAE_F8D4
from samplers import euler_sampler, euler_maruyama_sampler


# ══════════════════════════════════════════════════════════════
#  Model helpers
# ══════════════════════════════════════════════════════════════

def load_vae(device):
    """Load SD-VAE and latent normalisation stats."""
    vae = VAE_F8D4().to(device).eval()
    base = os.path.join(os.path.dirname(__file__), "pretrained_models")
    vae_ckpt = torch.load(
        os.path.join(base, "sdvae-ft-mse-f8d4.pt"),
        map_location=device, weights_only=False,
    )
    vae.load_state_dict(vae_ckpt)

    stats = torch.load(
        os.path.join(base, "sdvae-ft-mse-f8d4-latents-stats.pt"),
        map_location=device, weights_only=False,
    )
    scale = stats["latents_scale"].to(device).view(1, -1, 1, 1)
    bias  = stats["latents_bias"].to(device).view(1, -1, 1, 1)
    return vae, scale, bias


def load_model(ckpt_path, model_name, device, resolution=256):
    """Load a SiT model from checkpoint (EMA weights, strict=False)."""
    print(f"  Loading {ckpt_path} …")
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)

    ckpt_args = ckpt.get("args", None)
    qk_norm = False
    if ckpt_args is not None and hasattr(ckpt_args, "qk_norm"):
        qk_norm = ckpt_args.qk_norm

    latent_size = resolution // 8
    block_kwargs = {"fused_attn": False, "qk_norm": qk_norm}

    model = SiT_models[model_name](
        input_size=latent_size,
        in_channels=4,
        num_classes=1000,
        use_cfg=True,
        eval_mode=True,
        **block_kwargs,
    ).to(device)

    state_dict = ckpt.get("ema", ckpt.get("model", ckpt))
    filtered   = {k: v for k, v in state_dict.items() if "kv_proj" not in k}
    missing, unexpected = model.load_state_dict(filtered, strict=False)
    if missing:
        print(f"    [info] {len(missing)} missing keys")
    if unexpected:
        print(f"    [warn] {len(unexpected)} unexpected keys")

    model.eval()
    return model


# ══════════════════════════════════════════════════════════════
#  Sampling
# ══════════════════════════════════════════════════════════════

@torch.no_grad()
def generate_images(model, vae, latents_scale, latents_bias,
                    class_label: int, seed: int,
                    cfg_scale: float, num_steps: int,
                    mode: str, path_type: str,
                    resolution: int, device,
                    batch_size: int = 1):
    """
    Generate batch_size images with a fixed seed and class label.

    Returns: list of PIL.Image (RGB, resolution × resolution)
    """
    latent_size = resolution // 8
    torch.manual_seed(seed)

    z = torch.randn(batch_size, 4, latent_size, latent_size, device=device)
    y = torch.full((batch_size,), class_label, dtype=torch.long, device=device)

    sampling_kwargs = dict(
        model=model,
        latents=z,
        y=y,
        num_steps=num_steps,
        heun=False,
        cfg_scale=cfg_scale,
        guidance_low=0.0,
        guidance_high=1.0,
        path_type=path_type,
    )

    if mode == "sde":
        samples = euler_maruyama_sampler(**sampling_kwargs).to(torch.float32)
    else:
        samples = euler_sampler(**sampling_kwargs).to(torch.float32)

    samples = vae.decode(samples / latents_scale + latents_bias).sample
    samples = (samples + 1) / 2.0
    samples = torch.clamp(255.0 * samples, 0, 255) \
                   .permute(0, 2, 3, 1) \
                   .byte() \
                   .cpu() \
                   .numpy()

    return [Image.fromarray(s) for s in samples]


# ══════════════════════════════════════════════════════════════
#  Grid layout & plotting
# ══════════════════════════════════════════════════════════════

def make_grid_figure(
    images_a,        # list[list[PIL]] – images_a[ckpt_idx][group_idx]
    images_b,        # list[list[PIL]] – same shape
    method_a_label,
    method_b_label,
    ckpt_labels,     # e.g. ["100K", "200K", "400K"]
    group_titles,    # column-group titles (class name / "label=X seed=Y")
    save_path,
    dpi=200,
    cell_size=2.2,
    border_px=3,
    border_color=(220, 220, 220),
):
    """
    Draw the comparison grid matching Figure 8 style:

      ┌──────────────────────────────────────────────────────────┐
      │            [group 0]              [group 1]  …           │
      │          100K  200K  400K       100K  200K  400K  …      │
      │ Method A  img   img   img        img   img   img   …     │
      │ Method B  img   img   img        img   img   img   …     │
      └──────────────────────────────────────────────────────────┘

    Parameters
    ----------
    images_a / images_b : shape [n_ckpts][n_groups] PIL Images
    """
    n_ckpts  = len(ckpt_labels)
    n_groups = len(group_titles)
    n_methods = 2  # A and B

    # Total cols = groups × ckpts; rows = methods
    n_cols_total = n_groups * n_ckpts
    n_rows = n_methods

    fig_w = cell_size * n_cols_total + 1.2   # extra for row labels
    fig_h = cell_size * n_rows + 0.9         # extra for col headers

    fig = plt.figure(figsize=(fig_w, fig_h))

    # Two levels of column headers: group title + ckpt label
    # We'll use text annotations after imshow layout.

    # Build a flat grid: n_rows rows × n_cols_total cols
    # Leave a left margin column for row labels
    n_label_cols = 1
    gs = gridspec.GridSpec(
        n_rows, n_cols_total + n_label_cols,
        left=0.0, right=1.0, top=1.0, bottom=0.0,
        wspace=0.04, hspace=0.04,
    )

    all_method_images = [images_a, images_b]
    method_labels = [method_a_label, method_b_label]

    for row_idx, (method_imgs, m_label) in enumerate(
            zip(all_method_images, method_labels)):

        for grp_idx in range(n_groups):
            for ckpt_idx in range(n_ckpts):
                col_offset = n_label_cols + grp_idx * n_ckpts + ckpt_idx
                ax = fig.add_subplot(gs[row_idx, col_offset])

                img = method_imgs[ckpt_idx][grp_idx]
                ax.imshow(np.array(img))
                ax.set_xticks([])
                ax.set_yticks([])

                # Thin separator between groups (thicker left border)
                lw_left  = 2.0 if ckpt_idx == 0 and grp_idx > 0 else 0.5
                lw_right = 0.5
                for spine in ax.spines.values():
                    spine.set_linewidth(0.5)
                    spine.set_color("#cccccc")
                ax.spines["left"].set_linewidth(lw_left)
                ax.spines["left"].set_color("#888888" if lw_left > 1 else "#cccccc")

                # Row label (first column of each group-block on leftmost)
                if ckpt_idx == 0 and grp_idx == 0:
                    ax.set_ylabel(
                        m_label,
                        fontsize=7.5,
                        fontweight="bold",
                        rotation=90,
                        labelpad=4,
                        va="center",
                    )

                # Ckpt label on top row
                if row_idx == 0:
                    ax.set_title(ckpt_labels[ckpt_idx], fontsize=7, pad=2)

        # Add group title above the top row, spanning n_ckpts columns
        if row_idx == 0:
            for grp_idx, gtitle in enumerate(group_titles):
                col_start = n_label_cols + grp_idx * n_ckpts
                col_end   = col_start + n_ckpts - 1
                # Use an invisible "spanning" axis for text positioning
                ax_span = fig.add_subplot(
                    gs[0, col_start : col_end + 1]
                )
                ax_span.set_visible(False)
                ax_span.text(
                    0.5, 1.18, gtitle,
                    ha="center", va="bottom",
                    fontsize=8, fontweight="bold",
                    transform=ax_span.transAxes,
                )

    # "training iteration" arrow header
    ax0 = fig.add_subplot(gs[:, n_label_cols:])
    ax0.set_visible(False)

    plt.savefig(save_path, dpi=dpi, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)
    print(f"  Saved → {save_path}")


# ══════════════════════════════════════════════════════════════
#  Helpers
# ══════════════════════════════════════════════════════════════

def imagenet_classname(class_id: int) -> str:
    """Best-effort short class name from a lookup table."""
    NAMES = {
        0: "tench", 1: "goldfish", 2: "great white shark", 7: "hen",
        88: "macaw", 89: "sulphur-crested cockatoo", 130: "flamingo",
        207: "golden retriever", 281: "tabby cat", 325: "fire truck",
        340: "zebra", 388: "giant panda", 400: "hot air balloon",
        555: "fire engine", 569: "fire truck", 717: "pickup truck",
        724: "sports car", 849: "cheeseburger", 933: "cheeseburger",
        985: "daisy",
    }
    return NAMES.get(class_id, f"cls{class_id}")


def expand_range(range_arg, explicit_list):
    """
    Return a sorted list of integers.

    range_arg : None | [start, stop] | [start, stop, step]
    explicit_list : None | list[int]

    Priority: if range_arg is given it is used *in addition* to any
    explicit values; dedup + sort at the end.
    """
    values = list(explicit_list) if explicit_list else []
    if range_arg is not None:
        start = range_arg[0]
        stop  = range_arg[1]
        step  = range_arg[2] if len(range_arg) == 3 else 1
        values.extend(range(start, stop + 1, step))
    if not values:
        raise ValueError("Must supply at least one value via explicit list or range.")
    return sorted(set(values))


# ══════════════════════════════════════════════════════════════
#  Main
# ══════════════════════════════════════════════════════════════

def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate training-iteration comparison grid (Figure 8 style).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # ── Checkpoints ──────────────────────────────────────────
    parser.add_argument("--method-a-ckpts", nargs=3, required=True,
                        metavar="CKPT",
                        help="3 checkpoint paths for method A (100K, 200K, 400K)")
    parser.add_argument("--method-b-ckpts", nargs=3, required=True,
                        metavar="CKPT",
                        help="3 checkpoint paths for method B (100K, 200K, 400K)")
    parser.add_argument("--method-a-label", type=str, default="SiT-XL/2+iREPA",
                        help="Row label for method A")
    parser.add_argument("--method-b-label", type=str, default="SiT-XL/2+Attn.Scaf.",
                        help="Row label for method B")
    parser.add_argument("--ckpt-labels", nargs=3, default=["100K", "200K", "400K"],
                        metavar="LABEL",
                        help="Display labels for each checkpoint column")

    # ── Class labels (explicit list OR range) ─────────────────
    label_grp = parser.add_argument_group(
        "class labels",
        "Specify labels as an explicit list, a range, or both (values are merged)."
    )
    label_grp.add_argument("--class-labels", type=int, nargs="+", default=None,
                           metavar="CLS",
                           help="Explicit ImageNet class IDs, e.g. 325 555 933")
    label_grp.add_argument("--label-range", type=int, nargs="+", default=None,
                           metavar="N",
                           help="Range of class IDs: START STOP [STEP]  (inclusive). "
                                "E.g. --label-range 0 999  or  --label-range 300 350 5")

    # ── Seeds (explicit list OR range) ───────────────────────
    seed_grp = parser.add_argument_group(
        "seeds",
        "Specify seeds as an explicit list, a range, or both."
    )
    seed_grp.add_argument("--seeds", type=int, nargs="+", default=None,
                          metavar="S",
                          help="Explicit seed values, e.g. 0 1 2")
    seed_grp.add_argument("--seed-range", type=int, nargs="+", default=None,
                          metavar="N",
                          help="Range of seeds: START STOP [STEP]  (inclusive). "
                               "E.g. --seed-range 0 9  generates seeds 0..9")

    # ── Cartesian product mode ────────────────────────────────
    parser.add_argument("--cartesian", action="store_true", default=True,
                        help="(default ON) Generate all (label × seed) combinations. "
                             "Use --no-cartesian to pair label[i] with seed[i] only.")
    parser.add_argument("--no-cartesian", dest="cartesian", action="store_false",
                        help="Pair label[i] with seed[i] instead of all combinations.")

    # ── Sampling ─────────────────────────────────────────────
    parser.add_argument("--cfg-scale", type=float, default=4.0,
                        help="Classifier-free guidance scale (paper: 4.0)")
    parser.add_argument("--num-steps", type=int, default=250)
    parser.add_argument("--mode", type=str, default="ode",
                        choices=["ode", "sde"])
    parser.add_argument("--path-type", type=str, default="linear",
                        choices=["linear", "cosine"])
    parser.add_argument("--resolution", type=int, default=256,
                        choices=[256, 512])
    parser.add_argument("--model", type=str, default="SiT-XL/2",
                        choices=list(SiT_models.keys()))

    # ── Output ───────────────────────────────────────────────
    parser.add_argument("--out-dir", type=str, default="comparison_grids",
                        help="Directory to save output strips + combined grids")
    parser.add_argument("--grid-cols", type=int, default=6,
                        help="Max number of (label,seed) groups per combined grid PNG "
                             "(prevents huge canvases). Default 6.")
    parser.add_argument("--dpi", type=int, default=150)
    parser.add_argument("--cell-size", type=float, default=2.2,
                        help="Cell size in inches for each image cell")

    return parser.parse_args()


def main():
    args = parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    os.makedirs(args.out_dir, exist_ok=True)
    strips_dir = os.path.join(args.out_dir, "strips")
    os.makedirs(strips_dir, exist_ok=True)

    # ------------------------------------------------------------------
    # Build label list and seed list
    # ------------------------------------------------------------------
    all_labels = expand_range(args.label_range, args.class_labels)
    all_seeds  = expand_range(args.seed_range,  args.seeds)

    # Build (class_label, seed) pairs
    if args.cartesian:
        import itertools
        combos = list(itertools.product(all_labels, all_seeds))
    else:
        if len(all_labels) != len(all_seeds):
            raise ValueError(
                f"In --no-cartesian mode, number of labels ({len(all_labels)}) "
                f"must equal number of seeds ({len(all_seeds)})."
            )
        combos = list(zip(all_labels, all_seeds))

    n_combos = len(combos)
    n_ckpts  = 3

    print(f"\nLabels ({len(all_labels)}): {all_labels}")
    print(f"Seeds  ({len(all_seeds)}):  {all_seeds}")
    print(f"Combinations (label × seed): {n_combos}")
    print(f"Total images to generate:   "
          f"{n_combos} × {n_ckpts} ckpts × 2 methods = "
          f"{n_combos * n_ckpts * 2}")

    # ------------------------------------------------------------------
    # Load VAE
    # ------------------------------------------------------------------
    print("\nLoading VAE …")
    vae, latents_scale, latents_bias = load_vae(device)

    # ------------------------------------------------------------------
    # Load all 6 models
    # ------------------------------------------------------------------
    print("\nLoading method A models …")
    models_a = [
        load_model(p, args.model, device, args.resolution)
        for p in args.method_a_ckpts
    ]
    print("\nLoading method B models …")
    models_b = [
        load_model(p, args.model, device, args.resolution)
        for p in args.method_b_ckpts
    ]

    # ------------------------------------------------------------------
    # Generate images for every combination
    #   cache[method_idx][ckpt_idx][(class_label, seed)] = PIL.Image
    # ------------------------------------------------------------------
    # method_idx 0 = A, 1 = B
    all_models = [models_a, models_b]
    method_labels_list = [args.method_a_label, args.method_b_label]
    cache = [{} for _ in range(2)]

    total_gens = n_combos * n_ckpts * 2
    done = 0
    for m_idx, (models, m_label) in enumerate(
            zip(all_models, method_labels_list)):
        cache[m_idx] = {ck_i: {} for ck_i in range(n_ckpts)}
        for ck_i, (model, ck_lbl) in enumerate(
                zip(models, args.ckpt_labels)):
            for cl, seed in combos:
                done += 1
                print(f"  [{done}/{total_gens}] "
                      f"{m_label} / {ck_lbl} "
                      f"label={cl} seed={seed} …", end="\r")
                imgs = generate_images(
                    model=model,
                    vae=vae,
                    latents_scale=latents_scale,
                    latents_bias=latents_bias,
                    class_label=cl,
                    seed=seed,
                    cfg_scale=args.cfg_scale,
                    num_steps=args.num_steps,
                    mode=args.mode,
                    path_type=args.path_type,
                    resolution=args.resolution,
                    device=device,
                    batch_size=1,
                )
                cache[m_idx][ck_i][(cl, seed)] = imgs[0]
    print()

    # ------------------------------------------------------------------
    # Save one strip PNG per (label, seed) combination
    # Strip layout: 2 rows (method A/B) × 3 cols (100K/200K/400K)
    # ------------------------------------------------------------------
    print(f"\nSaving {n_combos} strips to {strips_dir} …")
    for combo_i, (cl, seed) in enumerate(combos):
        cls_name = imagenet_classname(cl)
        title = f"{cls_name}  label={cl}  seed={seed}"
        fig, axes = plt.subplots(
            2, n_ckpts,
            figsize=(args.cell_size * n_ckpts, args.cell_size * 2 + 0.5),
        )
        for ck_i, ck_lbl in enumerate(args.ckpt_labels):
            for m_idx, m_label in enumerate(method_labels_list):
                ax = axes[m_idx, ck_i]
                ax.imshow(np.array(cache[m_idx][ck_i][(cl, seed)]))
                ax.set_xticks([])
                ax.set_yticks([])
                if ck_i == 0:
                    ax.set_ylabel(m_label, fontsize=7, fontweight="bold",
                                  rotation=90, labelpad=3, va="center")
                if m_idx == 0:
                    ax.set_title(ck_lbl, fontsize=7, pad=2)

        fig.suptitle(title, fontsize=8, fontweight="bold")
        plt.tight_layout(rect=[0, 0, 1, 0.95])
        strip_name = f"cls{cl:04d}_seed{seed:04d}"
        strip_path = os.path.join(strips_dir, f"{strip_name}.png")
        plt.savefig(strip_path, dpi=args.dpi, bbox_inches="tight")
        plt.close(fig)
        print(f"  [{combo_i+1}/{n_combos}] {strip_path}")

    print("\nDone! 🎉")
    print(f"  Strips : {strips_dir}/")


if __name__ == "__main__":
    main()
